// Code generated by protoc-gen-go-grpc. DO NOT EDIT.
// versions:
// - protoc-gen-go-grpc v1.5.1
// - protoc             v5.28.3
// source: proto/proto.proto

package proto

import (
	context "context"
	grpc "google.golang.org/grpc"
	codes "google.golang.org/grpc/codes"
	status "google.golang.org/grpc/status"
)

// This is a compile-time assertion to ensure that this generated file
// is compatible with the grpc package it is being compiled against.
// Requires gRPC-Go v1.64.0 or later.
const _ = grpc.SupportPackageIsVersion9

const (
	GetCurrent_SendRequest_FullMethodName = "/proto.GetCurrent/SendRequest"
)

// GetCurrentClient is the client API for GetCurrent service.
//
// For semantics around ctx use and closing/ending streaming RPCs, please refer to https://pkg.go.dev/google.golang.org/grpc/?tab=doc#ClientConn.NewStream.
type GetCurrentClient interface {
	SendRequest(ctx context.Context, in *GetRequest, opts ...grpc.CallOption) (*GetReply, error)
}

type getCurrentClient struct {
	cc grpc.ClientConnInterface
}

func NewGetCurrentClient(cc grpc.ClientConnInterface) GetCurrentClient {
	return &getCurrentClient{cc}
}

func (c *getCurrentClient) SendRequest(ctx context.Context, in *GetRequest, opts ...grpc.CallOption) (*GetReply, error) {
	cOpts := append([]grpc.CallOption{grpc.StaticMethod()}, opts...)
	out := new(GetReply)
	err := c.cc.Invoke(ctx, GetCurrent_SendRequest_FullMethodName, in, out, cOpts...)
	if err != nil {
		return nil, err
	}
	return out, nil
}

// GetCurrentServer is the server API for GetCurrent service.
// All implementations must embed UnimplementedGetCurrentServer
// for forward compatibility.
type GetCurrentServer interface {
	SendRequest(context.Context, *GetRequest) (*GetReply, error)
	mustEmbedUnimplementedGetCurrentServer()
}

// UnimplementedGetCurrentServer must be embedded to have
// forward compatible implementations.
//
// NOTE: this should be embedded by value instead of pointer to avoid a nil
// pointer dereference when methods are called.
type UnimplementedGetCurrentServer struct{}

func (UnimplementedGetCurrentServer) SendRequest(context.Context, *GetRequest) (*GetReply, error) {
	return nil, status.Errorf(codes.Unimplemented, "method SendRequest not implemented")
}
func (UnimplementedGetCurrentServer) mustEmbedUnimplementedGetCurrentServer() {}
func (UnimplementedGetCurrentServer) testEmbeddedByValue()                    {}

// UnsafeGetCurrentServer may be embedded to opt out of forward compatibility for this service.
// Use of this interface is not recommended, as added methods to GetCurrentServer will
// result in compilation errors.
type UnsafeGetCurrentServer interface {
	mustEmbedUnimplementedGetCurrentServer()
}

func RegisterGetCurrentServer(s grpc.ServiceRegistrar, srv GetCurrentServer) {
	// If the following call pancis, it indicates UnimplementedGetCurrentServer was
	// embedded by pointer and is nil.  This will cause panics if an
	// unimplemented method is ever invoked, so we test this at initialization
	// time to prevent it from happening at runtime later due to I/O.
	if t, ok := srv.(interface{ testEmbeddedByValue() }); ok {
		t.testEmbeddedByValue()
	}
	s.RegisterService(&GetCurrent_ServiceDesc, srv)
}

func _GetCurrent_SendRequest_Handler(srv interface{}, ctx context.Context, dec func(interface{}) error, interceptor grpc.UnaryServerInterceptor) (interface{}, error) {
	in := new(GetRequest)
	if err := dec(in); err != nil {
		return nil, err
	}
	if interceptor == nil {
		return srv.(GetCurrentServer).SendRequest(ctx, in)
	}
	info := &grpc.UnaryServerInfo{
		Server:     srv,
		FullMethod: GetCurrent_SendRequest_FullMethodName,
	}
	handler := func(ctx context.Context, req interface{}) (interface{}, error) {
		return srv.(GetCurrentServer).SendRequest(ctx, req.(*GetRequest))
	}
	return interceptor(ctx, in, info, handler)
}

// GetCurrent_ServiceDesc is the grpc.ServiceDesc for GetCurrent service.
// It's only intended for direct use with grpc.RegisterService,
// and not to be introspected or modified (even as a copy)
var GetCurrent_ServiceDesc = grpc.ServiceDesc{
	ServiceName: "proto.GetCurrent",
	HandlerType: (*GetCurrentServer)(nil),
	Methods: []grpc.MethodDesc{
		{
			MethodName: "SendRequest",
			Handler:    _GetCurrent_SendRequest_Handler,
		},
	},
	Streams:  []grpc.StreamDesc{},
	Metadata: "proto/proto.proto",
}
