// Code generated by protoc-gen-go-grpc. DO NOT EDIT.
// versions:
// - protoc-gen-go-grpc v1.5.1
// - protoc             v5.28.3
// source: proto/service.proto

package proto

import (
	context "context"
	grpc "google.golang.org/grpc"
	codes "google.golang.org/grpc/codes"
	status "google.golang.org/grpc/status"
)

// This is a compile-time assertion to ensure that this generated file
// is compatible with the grpc package it is being compiled against.
// Requires gRPC-Go v1.64.0 or later.
const _ = grpc.SupportPackageIsVersion9

const (
	Receive_GetRequest_FullMethodName = "/proto.Receive/GetRequest"
)

// ReceiveClient is the client API for Receive service.
//
// For semantics around ctx use and closing/ending streaming RPCs, please refer to https://pkg.go.dev/google.golang.org/grpc/?tab=doc#ClientConn.NewStream.
type ReceiveClient interface {
	GetRequest(ctx context.Context, in *Request, opts ...grpc.CallOption) (*Reply, error)
}

type receiveClient struct {
	cc grpc.ClientConnInterface
}

func NewReceiveClient(cc grpc.ClientConnInterface) ReceiveClient {
	return &receiveClient{cc}
}

func (c *receiveClient) GetRequest(ctx context.Context, in *Request, opts ...grpc.CallOption) (*Reply, error) {
	cOpts := append([]grpc.CallOption{grpc.StaticMethod()}, opts...)
	out := new(Reply)
	err := c.cc.Invoke(ctx, Receive_GetRequest_FullMethodName, in, out, cOpts...)
	if err != nil {
		return nil, err
	}
	return out, nil
}

// ReceiveServer is the server API for Receive service.
// All implementations must embed UnimplementedReceiveServer
// for forward compatibility.
type ReceiveServer interface {
	GetRequest(context.Context, *Request) (*Reply, error)
	mustEmbedUnimplementedReceiveServer()
}

// UnimplementedReceiveServer must be embedded to have
// forward compatible implementations.
//
// NOTE: this should be embedded by value instead of pointer to avoid a nil
// pointer dereference when methods are called.
type UnimplementedReceiveServer struct{}

func (UnimplementedReceiveServer) GetRequest(context.Context, *Request) (*Reply, error) {
	return nil, status.Errorf(codes.Unimplemented, "method GetRequest not implemented")
}
func (UnimplementedReceiveServer) mustEmbedUnimplementedReceiveServer() {}
func (UnimplementedReceiveServer) testEmbeddedByValue()                 {}

// UnsafeReceiveServer may be embedded to opt out of forward compatibility for this service.
// Use of this interface is not recommended, as added methods to ReceiveServer will
// result in compilation errors.
type UnsafeReceiveServer interface {
	mustEmbedUnimplementedReceiveServer()
}

func RegisterReceiveServer(s grpc.ServiceRegistrar, srv ReceiveServer) {
	// If the following call pancis, it indicates UnimplementedReceiveServer was
	// embedded by pointer and is nil.  This will cause panics if an
	// unimplemented method is ever invoked, so we test this at initialization
	// time to prevent it from happening at runtime later due to I/O.
	if t, ok := srv.(interface{ testEmbeddedByValue() }); ok {
		t.testEmbeddedByValue()
	}
	s.RegisterService(&Receive_ServiceDesc, srv)
}

func _Receive_GetRequest_Handler(srv interface{}, ctx context.Context, dec func(interface{}) error, interceptor grpc.UnaryServerInterceptor) (interface{}, error) {
	in := new(Request)
	if err := dec(in); err != nil {
		return nil, err
	}
	if interceptor == nil {
		return srv.(ReceiveServer).GetRequest(ctx, in)
	}
	info := &grpc.UnaryServerInfo{
		Server:     srv,
		FullMethod: Receive_GetRequest_FullMethodName,
	}
	handler := func(ctx context.Context, req interface{}) (interface{}, error) {
		return srv.(ReceiveServer).GetRequest(ctx, req.(*Request))
	}
	return interceptor(ctx, in, info, handler)
}

// Receive_ServiceDesc is the grpc.ServiceDesc for Receive service.
// It's only intended for direct use with grpc.RegisterService,
// and not to be introspected or modified (even as a copy)
var Receive_ServiceDesc = grpc.ServiceDesc{
	ServiceName: "proto.Receive",
	HandlerType: (*ReceiveServer)(nil),
	Methods: []grpc.MethodDesc{
		{
			MethodName: "GetRequest",
			Handler:    _Receive_GetRequest_Handler,
		},
	},
	Streams:  []grpc.StreamDesc{},
	Metadata: "proto/service.proto",
}
