// Code generated by protoc-gen-go-grpc. DO NOT EDIT.
// versions:
// - protoc-gen-go-grpc v1.5.1
// - protoc             v5.28.2
// source: proto/service.proto

package proto

import (
	context "context"
	grpc "google.golang.org/grpc"
	codes "google.golang.org/grpc/codes"
	status "google.golang.org/grpc/status"
)

// This is a compile-time assertion to ensure that this generated file
// is compatible with the grpc package it is being compiled against.
// Requires gRPC-Go v1.64.0 or later.
const _ = grpc.SupportPackageIsVersion9

const (
	CakeService_EatCake_FullMethodName = "/proto.CakeService/EatCake"
)

// CakeServiceClient is the client API for CakeService service.
//
// For semantics around ctx use and closing/ending streaming RPCs, please refer to https://pkg.go.dev/google.golang.org/grpc/?tab=doc#ClientConn.NewStream.
type CakeServiceClient interface {
	EatCake(ctx context.Context, in *Request, opts ...grpc.CallOption) (*Reply, error)
}

type cakeServiceClient struct {
	cc grpc.ClientConnInterface
}

func NewCakeServiceClient(cc grpc.ClientConnInterface) CakeServiceClient {
	return &cakeServiceClient{cc}
}

func (c *cakeServiceClient) EatCake(ctx context.Context, in *Request, opts ...grpc.CallOption) (*Reply, error) {
	cOpts := append([]grpc.CallOption{grpc.StaticMethod()}, opts...)
	out := new(Reply)
	err := c.cc.Invoke(ctx, CakeService_EatCake_FullMethodName, in, out, cOpts...)
	if err != nil {
		return nil, err
	}
	return out, nil
}

// CakeServiceServer is the server API for CakeService service.
// All implementations must embed UnimplementedCakeServiceServer
// for forward compatibility.
type CakeServiceServer interface {
	EatCake(context.Context, *Request) (*Reply, error)
	mustEmbedUnimplementedCakeServiceServer()
}

// UnimplementedCakeServiceServer must be embedded to have
// forward compatible implementations.
//
// NOTE: this should be embedded by value instead of pointer to avoid a nil
// pointer dereference when methods are called.
type UnimplementedCakeServiceServer struct{}

func (UnimplementedCakeServiceServer) EatCake(context.Context, *Request) (*Reply, error) {
	return nil, status.Errorf(codes.Unimplemented, "method EatCake not implemented")
}
func (UnimplementedCakeServiceServer) mustEmbedUnimplementedCakeServiceServer() {}
func (UnimplementedCakeServiceServer) testEmbeddedByValue()                     {}

// UnsafeCakeServiceServer may be embedded to opt out of forward compatibility for this service.
// Use of this interface is not recommended, as added methods to CakeServiceServer will
// result in compilation errors.
type UnsafeCakeServiceServer interface {
	mustEmbedUnimplementedCakeServiceServer()
}

func RegisterCakeServiceServer(s grpc.ServiceRegistrar, srv CakeServiceServer) {
	// If the following call pancis, it indicates UnimplementedCakeServiceServer was
	// embedded by pointer and is nil.  This will cause panics if an
	// unimplemented method is ever invoked, so we test this at initialization
	// time to prevent it from happening at runtime later due to I/O.
	if t, ok := srv.(interface{ testEmbeddedByValue() }); ok {
		t.testEmbeddedByValue()
	}
	s.RegisterService(&CakeService_ServiceDesc, srv)
}

func _CakeService_EatCake_Handler(srv interface{}, ctx context.Context, dec func(interface{}) error, interceptor grpc.UnaryServerInterceptor) (interface{}, error) {
	in := new(Request)
	if err := dec(in); err != nil {
		return nil, err
	}
	if interceptor == nil {
		return srv.(CakeServiceServer).EatCake(ctx, in)
	}
	info := &grpc.UnaryServerInfo{
		Server:     srv,
		FullMethod: CakeService_EatCake_FullMethodName,
	}
	handler := func(ctx context.Context, req interface{}) (interface{}, error) {
		return srv.(CakeServiceServer).EatCake(ctx, req.(*Request))
	}
	return interceptor(ctx, in, info, handler)
}

// CakeService_ServiceDesc is the grpc.ServiceDesc for CakeService service.
// It's only intended for direct use with grpc.RegisterService,
// and not to be introspected or modified (even as a copy)
var CakeService_ServiceDesc = grpc.ServiceDesc{
	ServiceName: "proto.CakeService",
	HandlerType: (*CakeServiceServer)(nil),
	Methods: []grpc.MethodDesc{
		{
			MethodName: "EatCake",
			Handler:    _CakeService_EatCake_Handler,
		},
	},
	Streams:  []grpc.StreamDesc{},
	Metadata: "proto/service.proto",
}
